services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  urlsvc:
    image: url:0.0.1
    ports:
      - "8080:8080"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_URL=mongodb://mongodb:27017/sa
      - MONGO_DATABASE=demoCompose