server:
  port: 8080

spring:
  application:
  name: urlshortener
  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: 27017
      database: ${MONGO_DATABASE:demo}
      username: sa
      password: secret
      uri: ${MONGO_URL:mongodb://localhost:27017/sa}